### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by denieler**

### CODE REVIEW

**Comment by jackdoyle** [comment]
Thanks, @denieler but we made that change to package.json in order to solve several issues with NPM-related stuff, so reverting it isn't something we're looking to do. Can you explain what the issue is on your end that you're trying to solve?

**Comment by denieler** [comment]
Sure, I have trouble during building my project using Bower. So, it is
trying to get all 'main' files from all Bower packages, compile them and
concat in one J's file. But because main is pointing to the file that does
not exist it fails

**Comment by jackdoyle** [comment]
Fixed now?

**Comment by denieler** [comment]
After the change? Yes, sure. And this was in previous versions of the
library. Why you've changed that?

**Comment by bfred-it** [comment]
`package.json` didn't affect your workflow (bower), this PR wouldn't have fixed it.

For people using browserify/webpack/rollup, the change in 1.9.1 simplified imports from:

```js
require('gsap/src/uncompressed/utils/Draggable.js')
```

to just:

```js
require('gsap/Draggable')
```

**Comment by denieler** [comment]
It would help if you'd have this Tweek file in your root directory or
index.js file, but you don't have anything, am I right?

пн, 23 янв. 2017 г. в 9:57, Federico Brigante <notifications@github.com>:

**Comment by denieler** [comment]
and @bfred-it sure I have troubles not because of bower, but because of gulp package that is working under npm

**Comment by denieler** [comment]
@jackdoyle @bfred-it  thanks guys 👍 awesome reaction on the problem

**Pull request closed without merging**
