### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by jackdoyle** [comment]
We were asked to add that a while back, so I suspect some people need it there. Is there a particular reason it's causing problems for you?

**Comment by kkirsche** [comment]
No, it's just a pointless attribute which isn't used by Bower. Considering bower core development has basically been dead for awhile now, supporting bower isn't a great move anyway long term, so users relying on this are in for problems in the coming year.

**Comment by jackdoyle** [comment]
I see. Thanks for the info.

**Comment by kkirsche** [comment]
Also bower may be moving to NPM anyway: bower/bower#1520

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Pull request closed without merging**
