### PR TITLE
Allow animating attributes that were readonly and add more support for SVG elements

### PR DESCRIPTION
**Pull request by ianlet**
When animating some SVG elements, such as the radius of a circle, its center point, etc., the following error occurred : `TypeError: Cannot assign to read only property [...]`. This pull request adds supports for these `read-only` attributes and handle the animation of additional SVG elements/properties.

### CODE REVIEW

**Comment by jackdoyle** [comment]
Thanks for the suggestion, but your changes would break a bunch of other stuff and they're not necessary because all you need to do is use the AttrPlugin :) 

I'd strongly encourage you to check out this page that's dedicated to explaining SVG-specific stuff: http://greensock.com/svg-tips/

Example:
```javascript
TweenMax.to(svgElement, 1, {attr:{r:200}});
```

**Comment by ianlet** [comment]
Oh ok I didn't know about the AttrPlugin, my bad!

Sorry if I have waisted your time and thank you for the link. ;)

**Comment by jackdoyle** [comment]
No problem at all. Happy tweening!

**Comment by ianlet** [comment]
Thanks! Your library is awesome!

**Pull request closed without merging**
